Add task to check if WordPress is installed otherwise install
wearerequired/composer-deployer pull request #30
Opened 2021-10-21 12:20 UTC by grappler

fixes #29

2021-10-25 07:14 UTC, ocean90 requested changes

2021-10-25 07:14 UTC, ocean90 commented on res/deploy.tpl.php
> +	'wp:maybe_installed',
```suggestion
	'wp:install',
```

`maybe_installed` sounds like it only checks but does not install. Let's just name it `wp:install`?

2021-10-25 07:14 UTC, ocean90 commented on res/deploy.tpl.php
> +					run( "{{bin/wp}} core multisite-install --url=https://{$url} --title='New Install' --admin_user=required --admin_email=info@required.ch --skip-email --skip-config" );
```suggestion
					run( "{{bin/wp}} core multisite-install --url=https://{$url} --title=WordPress --admin_user=required --admin_email=info@required.ch --skip-email --skip-config" );
```

Keep it simple.

2021-10-25 07:14 UTC, ocean90 commented on res/deploy.tpl.php
> +
```suggestion
```

2021-10-25 07:14 UTC, ocean90 commented on res/deploy.tpl.php
> +					run( "{{bin/wp}} core install --url=https://{$url} --title='New Install' --admin_user=required --admin_email=info@required.ch --skip-email" );
```suggestion
					run( "{{bin/wp}} core install --url=https://{$url} --title=WordPress --admin_user=required --admin_email=info@required.ch --skip-email" );
```

2021-10-25 07:14 UTC, ocean90 commented on res/deploy.tpl.php
> +				$url          = run( 'set -o allexport; source wordpress/.env; set +o allexport; echo $_HTTP_HOST' );
Maybe name this `$host` or use `echo "https://$_HTTP_HOST"` to make it an URL?

2021-10-25 07:16 UTC, grappler commented on res/deploy.tpl.php
> +				$url          = run( 'set -o allexport; source wordpress/.env; set +o allexport; echo $_HTTP_HOST' );
```suggestion
				$url          = run( 'set -o allexport; source wordpress/.env; set +o allexport; echo "https://$_HTTP_HOST" );
```

2021-10-25 07:17 UTC, grappler commented on res/deploy.tpl.php
> +					run( "{{bin/wp}} core multisite-install --url=https://{$url} --title='New Install' --admin_user=required --admin_email=info@required.ch --skip-email --skip-config" );
```suggestion
					run( "{{bin/wp}} core multisite-install --url={$url} --title=WordPress --admin_user=required --admin_email=info@required.ch --skip-email --skip-config" );
```

2021-10-25 07:18 UTC, grappler commented on res/deploy.tpl.php
> +					run( "{{bin/wp}} core install --url=https://{$url} --title='New Install' --admin_user=required --admin_email=info@required.ch --skip-email" );
```suggestion
					run( "{{bin/wp}} core install --url={$url} --title=WordPress --admin_user=required --admin_email=info@required.ch --skip-email" );
```

2021-10-25 07:19 UTC, grappler commented on res/deploy.tpl.php
> +		'wp:maybe_installed',
```suggestion
		'wp:install',
```

2021-11-01 09:29 UTC, ocean90 commented on res/deploy.tpl.php
> +				$is_multisite = run( 'set -o allexport; source wordpress/.env; set +o allexport; echo $MULTISITE' );
I think we can combine this into one command. Something like this should work:

```php
$env = run( 'set -o allexport; source wordpress/.env; set +o allexport; echo "https://$_HTTP_HOST,$MULTISITE"' );
[ $url, $is_multisite ] = explode( ',', $env );
```

2021-11-01 11:01 UTC, grappler commented
I have changed the code and tested it again

2021-11-01 11:04 UTC, ocean90 approved these changes

2021-11-01 11:10 UTC, merged